---
# tasks file for install_besu
- name: check besu version
  command: besu --version
  register: besu_versions
  ignore_errors: True

- name: print besu version
  debug: var=besu_versions.stdout

- name: install besu
  block:
  - name: download besu
    apt: name=software-properties-common update_cache=yes 

  - name: Add an Apt signing key, uses whichever key is at the URL
    apt_key: 
      url: "{{ openjdk_apt_key_url }}"

  - name: Add APT repository for 'AdoptOpenJDK'
    shell: |
      add-apt-repository --yes {{ openjdk_apt_repo }}
    args:
      executable: /bin/bash

  - name: install jdk package
    apt: name={{ openjdk_name }} update_cache=yes 

  environment: "{{ env|d({}) }}"
  when: besu_versions.rc != 1
  become: true
