---
- name: Create configuration directory
  file:
    path: "{{ besu_node_dir }}"
    state: directory
    owner: "{{ besu_user }}"
    group: "{{ besu_group }}"
    recurse: yes
  become: true

- name: infos 1
  debug:
    var: enode

- name: set config file type
  set_fact:
    besu_bootnodes: '{{ enode }}'
    cacheable: yes
  when: is_boot_node == False

- name: infos 2
  debug:
    var: besu_bootnodes

- name: Generate node config file
  template:
    src: "{{ besu_config_template }}"
    dest: "{{ besu_node_dir }}/config.toml"
    owner: "{{ besu_user }}"
    group: "{{ besu_group }}"
    mode: 0644
  become: true
  register: config_toml
  when: True

# - name: Set updated optionally to trigger a systemd restart at the end
#   set_fact:
#     besu_state_updates: "{{ besu_state_updates + ['besu.config_toml'] }}"
#   when: config_toml is changed

- name: Create data directory
  file:
    path: "{{ besu_data_dir }}"
    state: directory
    owner: "{{ besu_user }}"
    group: "{{ besu_group }}"
    recurse: yes
  become: true
