---
  all:
    hosts:
      controller:  # control machine
        ansible_host: localhost
        ansible_connection: local
      val-01:
        ansible_host: 193.168.100.101
        ansible_user: vagrant
        #private_key_file: ~/.vagrant.d/insecure_private_key
      val-02:
        ansible_host: 193.168.100.102
        ansible_user: vagrant
        #private_key_file: ~/.vagrant.d/insecure_private_key
      val-03:
        ansible_host: 193.168.100.103
        ansible_user: vagrant
        #private_key_file: ~/.vagrant.d/insecure_private_key
      val-04:
        ansible_host: 193.168.100.104
        ansible_user: vagrant
        #private_key_file: ~/.vagrant.d/insecure_private_key
  validaters:
    hosts:
      val-01:
      val-02:
      val-03:
      val-04:
  test4node:
    hosts:
      val-02:
  test:
    hosts:
      val-01:

  