---
# defaults file for make_besu_config
# 재정의 할수 있는 기본 변수

besu_nodes: 1
besu_chain_id: 2020
besu_ibft_blockperiodseconds: 2
besu_ibft_epochlength: 30000
besu_ibft_requesttimeoutseconds: 10

# option: all (genesis.json, node private key, besu config), genesis(genesis.json only), config(besu config only)
roll_option: genesis 
# option: False (없거나 변경된 경우에만 생성)
force: yes
# Option
#is_boot_node: false

# User and group
#besu_user: besu
#besu_group: "{{ besu_user }}"

# Version
#besu_version: "1.3.8"

# Version to install
#besu_download_url: "https://bintray.com/hyperledger-org/besu-repo/download_file?file_path=besu-{{ besu_version }}.tar.gz"

# Directory paths
besu_base_dir: "/opt/besu"
#besu_install_dir: "{{ besu_base_dir }}/besu-{{ besu_version }}"
#besu_current_dir: "{{ besu_base_dir }}/current"
besu_exec_binary: "{{ besu_base_dir }}/current/bin/besu"
#besu_node_private_key_file: ""
besu_config_dir: "/etc/besu"
besu_config_template: "config.toml.j2"
#besu_data_dir: "{{ besu_base_dir }}/data"
#besu_log_dir: "/var/log/besu"
#besu_profile_file: "/etc/profile.d/besu-path.sh" # ??

# New defined
besu_temp_dir: "{{ besu_config_dir }}/temp"
besu_node_dir: "{{ besu_config_dir }}/{{ inventory_hostname }}"
besu_genesis_path: "{{ besu_node_dir }}/genesis.json"
#besu_consensus: "ibft 2.0"
besu_genesis_config_template: "ibftConfigFile.json.j2"
#besu_boot_enode_path: "./generated/{{ inventory_hostname }}-boot-node-key.pub"
#besu_static_enode_path: "./generated/{{ inventory_hostname }}-static-node-key.pub"
besu_boot_enode_post_fix: "-boot-node-key.pub"
besu_static_enode_post_fix: "-static-node-key.pub"

# Modified
besu_node_private_key_file: "{{ besu_node_dir }}/key"
besu_data_dir: "{{ besu_node_dir }}/data"

# Managed service config
# besu_managed_service: true
# besu_systemd_state: restarted
# besu_systemd_template: besu.service.j2
# besu_systemd_dir: /etc/systemd/system
# macOS
# besu_launchd_template: org.hyperledger.besu.plist.j2
# besu_launchd_dir: /Library/LaunchAgents

# Besu config
besu_host_ip: ""
besu_default_ip: "127.0.0.1"
besu_network: mainnetXXX
#besu_sync_mode: FAST
besu_sync_mode: FULL
besu_log_level: INFO
besu_p2p_port: 30303
besu_min_gas: 1000
besu_rpc_http_enabled: "true"
besu_rpc_http_host: 0.0.0.0
besu_rpc_http_port: 8545
besu_rpc_http_api: ["ADMIN", "DEBUG", "NET", "ETH", "MINER", "WEB3"]
besu_rpc_http_cors_origins: ["all"]
besu_rpc_ws_enabled: "true"
besu_rpc_ws_host: 0.0.0.0
besu_rpc_ws_port: 8546
besu_graphql_http_enabled: "true"
besu_graphql_http_host: 0.0.0.0
besu_graphql_http_port: 8547
besu_graphql_http_cors_origins: ["all"]
besu_metrics_enabled: "true"
besu_metrics_host: 0.0.0.0
besu_metrics_port: 9545
besu_bootnodes: []
besu_host_whitelist: ["*"]
besu_cmdline_args: ""
besu_env_opts: ""

# internal state to maintain idempotency
# besu_state_updates: []
