---
# tasks file for install_openjdk
- name: Ensure configuration
  block:
  - fail:
      msg: You must set "openjdk_version" for this role to run
    when: openjdk_version is not defined
  - name: check input openjdk_version 
    fail:
      msg: 'Wrong range "openjdk_version": {{ openjdk_version }}'
    when: ( openjdk_version|int < 11 ) or ( openjdk_version|int > max_openjdk_version|int )

- name: Get installed Java version
  command: java --version
  register: java_version_infos
  ignore_errors: True

# - name: Print java version
#   debug: 
#     var: java_version_infos.stdout
#   when: java_version_infos.rc == 0

# - name: check AdoptOpenJDK
#   command: javac --version
#   register: javac_version_infos
#   when: java_version_infos.rc == 0
#   ignore_errors: True

# - name: print javac version
#   debug: 
#     var: javac_version_infos
#   when: javac_version_infos is defined

- name: ensure installed java version for besu
  block:
    - name: Show Java version
      debug: 
        var: java_version_infos.stdout
    - name: Check jdk type name
      fail:
        msg: Other type JDK version (need {{ openjdk_name_comp }})
      when: java_version_infos.stdout.find(openjdk_name_comp) == -1
    - name: Check jdk version
      # fail:
      #   msg: 'Wrong JDK Version (installed version: {{ java_version_infos.stdout }})'
      # when: java_version_infos.stdout.find(openjdk_version_comp) == -1
      set_fact:
        need_force_update: False
      when: True
  when: java_version_infos.rc == 0

- name: install {{ openjdk_name }}
  block:
  # - name: install software-properties-common packages
  #   apt: 
  #     name: software-properties-common 
  #     update_cache: yes 

  - name: Add an apt signing key, uses whichever key is at the URL
    apt_key: 
      url: "{{ openjdk_apt_key_url }}"
    when: need_force_update == True
    # 왜 에러발생??
    # - name: Add APT repository for 'AdoptOpenJDK'
    #   apt_repository:
    #     repo: deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ stable main
    #     state: present
    #     update_cache: true
  - name: Add apt repository for 'AdoptOpenJDK'
    shell: |
      add-apt-repository --yes {{ openjdk_apt_repo }}
    args:
      executable: /bin/bash
    when: need_force_update == True

  - name: Install jdk package
    apt: 
      name: [ software-properties-common, '{{ openjdk_name }}' ]
      update_cache: yes 

  environment: "{{ env|d({}) }}"
  when: True # java_version_infos.rc != 0
  become: true

# - name: Update Result Ref
#   set_fact:
#     openjdk_updated: 'aaaaa'
#     openjdk_kkkkk: dfvgg
#   when: true

# - debug: var=hostvars[inventory_hostname]
#   when: inventory_hostname == 'val-02'
